name: Build & Publish
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Cache ✨
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: install dependencies
        run: yarn install
      - name: test
        run: yarn test:cov
      - uses: mikeal/merge-release@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}